receivers:
  otlp:
    protocols:
      http:
        include_metadata: true
        endpoint: :4318

exporters:
  jaeger:
    endpoint: jaeger-collector:14250
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    target_info:
      enabled: true

connectors:
  spanmetrics:
    namespace: span.metrics
    histogram:
      explicit:
        buckets:
    dimensions:
      - name: http.method
        default: GET
      - name: http.status_code
    dimensions_cache_size: 1000
    aggregation_temporality: 'AGGREGATION_TEMPORALITY_CUMULATIVE'
    metrics_flush_interval: 5s

# processors:
#   batch:

extensions:
  health_check: 
    endpoint: :13133

service:
  extensions: [ health_check ]
  pipelines:
    traces:
      receivers: [otlp]
      # processors: [batch]
      exporters: [spanmetrics, jaeger]
    
    metrics:
      receivers: [spanmetrics]
      exporters: [prometheusremotewrite]
